import { GoogleGenAI } from "@google/genai";
import * as z from "zod"
import dotenv from "dotenv"

dotenv.config()
import puppeteer from "puppeteer"


const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GEMINI_API_KEY
})

async function invokeGwminiAI() {


    const res = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: "Hello gemini| explain what is interview"
    })
    console.log(res.text);

}
const interviewReportSchema = {
    type: "object",
    description: "A full interview preparation report generated by comparing a candidate's resume and self description against a job description",
    properties: {
        matchScore: {
            type: "integer",
            description: "How well the resume matches the job description, from 0 to 100"
        },
        technicalQuestions: {
            type: "array",
            description: "Exactly 3 technical interview questions.",
            items: {
                type: "object",
                properties: {
                    question: {
                        type: "string",
                        description: "The technical interview question."
                    },
                    intension: {
                        type: "string",
                        description: "Explain what the interviewer is testing in 1-2 sentences."
                    },
                    answer: {
                        type: "string",
                        description: "Give a concise interview-ready answer in 3-5 sentences."
                    }
                },
                required: ["question", "intension", "answer"]
            }
        },
        behavioralQuestions: {
            type: "array",
            description: "Exactly 2 behavioral interview questions.",
            items: {
                type: "object",
                properties: {
                    question: {
                        type: "string",
                        description: "The behavioral interview question."
                    },
                    intension: {
                        type: "string",
                        description: "Explain what the interviewer is evaluating in 1-2 sentences."
                    },
                    answer: {
                        type: "string",
                        description: "Give a concise interview-ready answer in 3-5 sentences."
                    }
                },
                required: ["question", "intension", "answer"]
            }
        },
        skillGap: {
            type: "array",
            description: "Maximum 5 of the most important skill gaps.",
            items: {
                type: "object",
                properties: {
                    skill: {
                        type: "string",
                        description: "The missing or weak skill."
                    },
                    sevarity: {
                        type: "string",
                        enum: ["low", "medium", "hard"],
                        description: "Severity of the skill gap."
                    }
                },
                required: ["skill", "sevarity"]
            }
        },
        preparationPlan: {
            type: "array",
            description: "Exactly 3 days of concise interview preparation.",
            items: {
                type: "object",
                properties: {
                    day: {
                        type: "number",
                        description: "Preparation day number."
                    },
                    focus: {
                        type: "string",
                        description: "Main focus for the day."
                    },
                    tasks: {
                        type: "array",
                        description: "3-4 practical tasks for the day.",
                        items: {
                            type: "string"
                        }
                    }
                },
                required: ["day", "focus", "tasks"]
            }
        }
    },
    required: ["matchScore", "technicalQuestions", "behavioralQuestions", "skillGap", "preparationPlan"]
};
async function generateIntervieweReport({ resume, selfDescription, jobDecsription }) {
    const prompt = `
Analyze the candidate against the job description.

JOB DESCRIPTION:
${jobDecsription}

RESUME:
${resume}

SELF DESCRIPTION:
${selfDescription}

Create a concise interview preparation report.

Requirements:
- Match score from 0-100.
- Exactly 3 technical interview questions.
- Exactly 2 behavioral interview questions.
- Identify the most important skill gaps.
- Create a practical 3-day preparation plan.
- Keep explanations concise.
- Keep interview answers to 3-5 sentences.
- Base the analysis only on the provided information.
`;
    // for test
    console.log("Resume:", resume);
    console.log("Job Description:", jobDecsription);
    console.log("Self Description:", selfDescription);
    console.log("Resume characters:", resume?.length || 0);
    console.log("Job description characters:", jobDecsription?.length || 0);
    console.log("Self description characters:", selfDescription?.length || 0);
    console.time("Gemini Interview Report");
    const res = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: interviewReportSchema
        }
    })
    // for test
    console.log(
    "Gemini response characters:",
    res.text?.length || 0
);
    console.timeEnd("Gemini Interview Report");
    const JsonContent = JSON.parse(res.text)
    console.log(JsonContent);

    return JsonContent

}
// for pdf format
async function generatePdfFormatHtml(htmlContent) {
    let browser;
    try {
        browser = await puppeteer.launch({
            headless: "new",
            args: ["--no-sandbox", "--disable-setuid-sandbox"]
        });

        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: "networkidle0" });

        const pdfBuffer = await page.pdf({
            format: "A4",
            margin: {
                top: '20mm',
                bottom: "20mm",
                left: "15mm",
                right: "15mm"
            }
        });

        return pdfBuffer;
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

function parseGeminiJsonResponse(response) {
    const rawText = response?.text
        || response?.candidates?.[0]?.content?.parts
            ?.map(part => part?.text || "")
            .join("")
        || "";

    const cleanedText = rawText
        .replace(/^```(?:json)?\s*/i, "")
        .replace(/\s*```$/i, "")
        .trim();

    if (!cleanedText) {
        throw new Error("Gemini returned an empty response for the resume HTML.");
    }

    return JSON.parse(cleanedText);
}

async function generateResumePdf({ resume, selfDescription, jobDecsription }) {
    const resumePdfSchema = {
        type: "object",
        description: "The generated resume as a single HTML document",
        properties: {
            html: {
                type: "string",
                description: "The HTML content of the resume which can be converted to PDF using any library like puppeteer"
            }
        },
        required: ["html"]
    }

    const prompt = `
                     Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDecsription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1 page long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
               `

    const res = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: resumePdfSchema
        }
    });

    const jsonContent = parseGeminiJsonResponse(res);

    if (!jsonContent?.html || typeof jsonContent.html !== "string") {
        throw new Error("AI returned an invalid resume payload.");
    }

    const pdfBuffer = await generatePdfFormatHtml(jsonContent.html);
    return pdfBuffer;
}
// export default invokeGwminiAI
export { generateIntervieweReport, generateResumePdf }