import { GoogleGenAI } from "@google/genai";
import * as z from "zod";
import dotenv from "dotenv"

dotenv.config()
import puppeteer from "puppeteer"


const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GEMINI_API_KEY
})

async function invokeGwminiAI() {
    const res = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: "Hello gemini| explain what is interview"
    })
    console.log(res.text);

}
const interviewReportSchema = {
    type: "object",
    description: "A full interview preparation report generated by comparing a candidate's resume and self description against a job description",
    properties: {
        matchScore: {
            type: "integer",
            description: "How well the resume matches the job description, from 0 to 100"
        },
        technicalQuestions: {
            type: "array",
            description: "A list of 3-5 technical interview questions tailored to the job description, testing skills the role requires",
            items: {
                type: "object",
                description: "A single technical question paired with why it's being asked and a strong sample answer",
                properties: {
                    question: {
                        type: "string",
                        description: "A technical interview question relevant to the job description"
                    },
                    intension: {
                        type: "string",
                        description: "Why this question is being asked — what skill or knowledge it tests"
                    },
                    answer: {
                        type: "string",
                        description: "How to answer this question, what points to cover, what approach to take etc"
                    }
                },
                required: ["question", "intension", "answer"]
            }
        },
        behavioralQuestions: {
            type: "array",
            description: "A list of 2-3 behavioral interview questions assessing soft skills, past experience, and how the candidate handles real work situations",
            items: {
                type: "object",
                description: "A single behavioral question paired with why it's being asked and a strong sample answer",
                properties: {
                    question: {
                        type: "string",
                        description: "A behavioral interview question, typically starting with 'Tell me about a time...' or similar"
                    },
                    intension: {
                        type: "string",
                        description: "What trait, skill, or experience this question is trying to uncover"
                    },
                    answer: {
                        type: "string",
                        description: "How to answer this question, what points to cover, what approach to take etc"
                    }
                },
                required: ["question", "intension", "answer"]
            }
        },
        skillGap: {
            type: "array",
            description: "A list of skills the job description requires that are missing or weak in the candidate's resume, each rated by how critical the gap is",
            items: {
                type: "object",
                description: "A single missing or weak skill with a severity rating",
                properties: {
                    skill: {
                        type: "string",
                        description: "The name of the skill that is missing or underrepresented in the resume relative to the job description"
                    },
                    sevarity: {
                        type: "string",
                        enum: ["low", "medium", "hard"],
                        description: "How critical this skill gap is for the role — low if minor/nice-to-have, hard if it's a core requirement the candidate lacks"
                    }
                },
                required: ["skill", "sevarity"]
            }
        },
        preparationPlan: {
            type: "array",
            description: "A day-by-day study plan (3-5 days) to help the candidate prepare for the interview, prioritizing the identified skill gaps",
            items: {
                type: "object",
                description: "A single day's focus area and the specific tasks to complete that day",
                properties: {
                    day: {
                        type: "integer",
                        description: "The day number in the preparation plan, starting at 1"
                    },
                    focus: {
                        type: "string",
                        description: "The main topic or skill area to focus on for this day"
                    },
                    tasks: {
                        type: "array",
                        description: "A list of specific, actionable tasks to complete on this day to build toward the day's focus area",
                        items: {
                            type: "string",
                            description: "A single actionable preparation task"
                        }
                    }
                },
                required: ["day", "focus", "tasks"]
            }
        }
    },
    required: ["matchScore", "technicalQuestions", "behavioralQuestions", "skillGap", "preparationPlan"]
};
async function generateIntervieweReport({ resume, selfDescription, jobDecsription }) {
    const prompt = `
You are an expert technical interviewer and career coach.
 
Given the candidate's resume, self description, and the job description below,
generate a full interview preparation report.
 
Job Description:
${jobDecsription}
 
Resume:
${resume}
 
Candidate Self Description:
${selfDescription}
 
Generate:
- A matchScore (0-100) for how well the resume fits the job description
- 3-5 technical interview questions relevant to the role, each with the intention behind asking it and a strong sample answer
- 2-3 behavioral interview questions, same structure
- A list of skill gaps between the resume and job description, with a severity rating
- A day-by-day preparation plan (3-5 days) with a focus area and specific tasks per day
`;

const res=await ai.models.generateContent({
    model:"gemini-3.5-flash",
    contents:prompt,
    config:{
        responseMimeType:"application/json",
        responseSchema:interviewReportSchema
    }
})
const JsonContent=JSON.parse(res.text)
console.log(JsonContent);

return JsonContent

}
// for pdf format
async function generatePdfFormatHtml(htmlContent){
    const browser=await puppeteer.launch()
    const page=await browser.newPage()
    await page.setContent(htmlContent,{waitUntil:"networkidle0"})

    const pdfBuffer=await page.pdf({
        format:"A4",margin:{
            top:'20mm',
            bottom:"20mm",
            left:"15mm",
            right:"15mm"
        }
    })
}
// export default invokeGwminiAI
export default generateIntervieweReport